# Generated by Django 5.1.5 on 2025-02-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_category_coupon_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
